version: '3.9'

services:
    server:
        image: 215636381729.dkr.ecr.eu-west-1.amazonaws.com/sonnylabs:latest
        build: .
        deploy:
            replicas: 1
            resources:
                limits:
                    memory: '500M'
        ports:
        - "3000:3000"
        environment:
            DATABASE_URL: "postgresql://postgres:password@db:5432/postgres"
            NPROCS: 1
            RUST_LOG: info
        depends_on:
        - db

    server-test:
        build:
            context: .
            target: test
        profiles:
        - task
        environment:
            DATABASE_URL: "postgresql://postgres:password@db:5432/postgres"
        depends_on:
        - db

    db:
        image: docker.io/postgres:16.2-bookworm
        restart: always
        environment:
            POSTGRES_PASSWORD: password
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
        - './_pg_data:/var/lib/postgresql/data'
        ports:
        - '5432:5432'
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 20

    db-init:
        image: docker.io/postgres:16.2-bookworm
        #entrypoint: ["bash"]
        entrypoint: [
            'bash', '-c',
            "cat /mnt/db/*.sql | psql \"$${DATABASE_URL}\""
        ]
        environment:
            DATABASE_URL: "postgresql://postgres:password@db:5432/postgres"
        volumes:
        - './db:/mnt/db'
        depends_on:
            db:
                condition: service_healthy
        profiles:
        - task

    db-seed:
        build: .
        entrypoint: ["/app/db-seed"]
        environment:
            DATABASE_URL: "postgresql://postgres:password@db:5432/postgres"
        depends_on:
            db:
                condition: service_healthy
        profiles:
        - task
