version: '3.9'

services:
    server:
        image: 215636381729.dkr.ecr.eu-west-1.amazonaws.com/sonnylabs:latest
        build: .
        deploy:
            replicas: 1
            resources:
                limits:
                    memory: '600M'
        ports:
        - "80:3000"
        environment:
            NPROCS: 1
            RUST_LOG: info
